/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GemaltoDongle */

#ifndef _Included_GemaltoDongle
#define _Included_GemaltoDongle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GemaltoDongle
 * Method:    getDongleInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GemaltoDongle_getDongleInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
