/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_beyondsoft_utils_GemaltoDongle */

#ifndef _Included_com_beyondsoft_utils_GemaltoDongle
#define _Included_com_beyondsoft_utils_GemaltoDongle
#ifdef __cplusplus
extern "C" {
#endif

#define FUNCNAME(x)   Java_com_beyondsoft_utils_GemaltoDongle_##x


/*
 * Class:     com_beyondsoft_utils_GemaltoDongle
 * Method:    getDongleId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL FUNCNAME(getDongleId)
  (JNIEnv *, jobject);

/*
 * Class:     com_beyondsoft_utils_GemaltoDongle
 * Method:    getDongleInfo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL FUNCNAME(getDongleInfo)
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
