/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GemaltoDongle */

#ifndef _Included_GemaltoDongle
#define _Included_GemaltoDongle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GemaltoDongle
 * Method:    getDongleInfo
 * Signature: (J)Ljava/lang/String;
 */

#define FUNCNAME(x)   Java_GemaltoDongle_##x

JNIEXPORT jstring JNICALL FUNCNAME(getDongleInfo)
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
